# Site settings
title: lodsb.org - music, dev, research
email: lodsb(at)lodsb.org
short-description: Hello World
description: XXX
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
