# Site settings
title: lodsb.org - music, dev, research
email: lodsb(at)lodsb.org
short-description: piep
description: music, dev, research
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lodsb.org" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
